// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingLotSystem.Data;

#nullable disable

namespace ParkingLotSystem.Migrations
{
    [DbContext(typeof(ParkingLotSystemContext))]
    [Migration("20260106124311_Subscriptions")]
    partial class Subscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingLotSystem.Models.ParkingLot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID");

                    b.ToTable("ParkingLot");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.PlanParkingLot", b =>
                {
                    b.Property<int>("SubscriptionPlanID")
                        .HasColumnType("int");

                    b.Property<int>("ParkingLotID")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionPlanID", "ParkingLotID");

                    b.HasIndex("ParkingLotID");

                    b.ToTable("PlanParkingLot");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.Subscriber", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Subscriber");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.Subscription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubscriberID")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriptionPlanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SubscriberID");

                    b.HasIndex("SubscriptionPlanID");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID");

                    b.ToTable("SubscriptionPlan");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.PlanParkingLot", b =>
                {
                    b.HasOne("ParkingLotSystem.Models.ParkingLot", "ParkingLot")
                        .WithMany("PlanParkingLots")
                        .HasForeignKey("ParkingLotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingLotSystem.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("PlanParkingLots")
                        .HasForeignKey("SubscriptionPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLot");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.Subscription", b =>
                {
                    b.HasOne("ParkingLotSystem.Models.Subscriber", "Subscriber")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriberID");

                    b.HasOne("ParkingLotSystem.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanID");

                    b.Navigation("Subscriber");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.ParkingLot", b =>
                {
                    b.Navigation("PlanParkingLots");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.Subscriber", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ParkingLotSystem.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("PlanParkingLots");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
